### ISSUE TITLE
Crash when shaping produces many glyphs

### ISSUE THREAD

**Issue by dscorbett** [simoncozens/crowbar#36]
Given [this font](https://github.com/dscorbett/duployan-test/blob/c0e467c851ce184ab5026056c95c5d438a79648d/assets/fonts/Duployan-Regular.otf) and the input string “𛰁” (U+1BC01 DUPLOYAN LETTER X), Crowbar crashes: the page goes completely blank. That single-character input produces 253 glyphs.

**Comment by simoncozens** [comment]
Could you try upping the shaping buffer size here:

https://github.com/simoncozens/crowbar/blob/fbfbc41fca9afa146d81b91b10699348166b1283/src/hbjs.js#L358

If that doesn't work, try the overall memory pool here:

https://github.com/simoncozens/crowbar/blob/fbfbc41fca9afa146d81b91b10699348166b1283/src/index.tsx#L19

If *that* doesn't work, it's probably the SVG buffer. WebAssembly static memory management is a pain like that.

**Comment by dscorbett** [comment]
I changed them to `1024 * 1024 * 1024 * 1024` and `8000`. Neither helped. When running it locally, it showed an error message: “SyntaxError: JSON.parse: expected ',' or ']' after array element at line 1 column 23 of the JSON data”. Indeed, `trace` was `'[[{"g":113665,"cl":0}]'` followed by many null characters.

**Comment by nederhof** [comment]
Got the same issue: page going blank on just 3 characters. Tried much as dscorbett: 
`var bufLen = 1024 * 1024 * 1024;`
but then:
```
Uncaught RuntimeError: table index is out of bounds
    at 00129a16:0x330c0
    at 00129a16:0x374b0
    at 00129a16:0x37c8f
    at Object.shapeWithTrace (hbjs.js:423:1)
    at CrowbarFont.shapeTrace (CrowbarFont.ts:181:1)
    at OutputArea (OutputArea.tsx:85:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
```
With:
`var bufLen = 1024 * 1024 * 1024 * 1024;`
I get:
```
Uncaught RuntimeError: memory access out of bounds
    at 00129a16:0x215d2
    at 00129a16:0x3545b
    at 00129a16:0x359e4
    at 00129a16:0x37c8f
    at Object.shapeWithTrace (hbjs.js:423:1)
    at CrowbarFont.shapeTrace (CrowbarFont.ts:181:1)
    at OutputArea (OutputArea.tsx:85:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
```
Also tried to insert at line 19 of mentioned file:
`results.instance.exports.memory.grow(800);`
but that did not compile.
